### ISSUE TITLE
Update fresnel / document supported versions

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-examples#16]
## File name

I had issues running the latest build of `fresnel` (with API changes newer than 0.12). The specific issues were with cameras, `orthographic` vs. `Orthographic`.

## To fix

Document supported fresnel version numbers.
When the next release of fresnel comes out, an update will be needed.

## Can you fix it?

I'm currently filing a lot of issues and am not able to commit to fixing all of them at this time.

**Comment by joaander** [comment]
I added version checks in the new tutorials for v3.
