### ISSUE TITLE
hoomd-examples outline

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-examples#2]
# hoomd-examples rewrite

hoomd-examples needs significant improvement to better inform users. Recognizing that users will copy and paste anything in the examples, all examples must be exemplars of research workflow best practices. The tutorials will be broken up into the following sections.

**We need your help!** Please review the outline below and let us know what examples you think would be useful in the documentation. I will update this description with the suggestions to complete the outline for the new HOOMD examples.

## Basic tutorials

Basic tutorials introduce the user to the essential elements of a HOOMD simulation via short examples with extended descriptions. Later example scripts may assume that the user is familiar with these concepts and do not need to re-introduce them.

* Introduction
* Executing scripts _(jupyter notebook and command line)_
* Introducing contexts _(including cpu, gpu modes, and launching with mpirun)_
* Specifying the initial condition _(via gsd file, also describe the commonly used per-particle properties)_
* MD simulations _(read_gsd, nlist configuration, integrator, run)_
* HPMC simulations _(read_gsd, integrator, run)_
* Log file output _(analyze.log)_
* Trajectory output _(dump.gsd)_
* Saving trajectory metadata _(e.g. dumping MC shape information)_
* Visualizing trajectories _(explains the fresnel visualization helper script, also links to OVITO, VMD, plato-draw)_

## Examples

Examples demonstrate research-relevant use cases of HOOMD with simple, easy-to-understand code along with Markdown cells that explain it and a link to the research paper. The examples should include code that initializes the system in a gsd file, including compression to the target density (if applicable), and the simulation configuration and execution. Examples should be self-contained to the extent that is possible _(i.e. no reliance on signac workspaces or extensive json configurations)_ with parameters hard coded or specified as variables in the script. Where possible, examples should be run on a small number of particles so that a single cpu can run the example and get meaningful output in a few minutes. When possible, the example should utilize the visualization helper script to render the output trajectory and/or plot log output so that the user may adjust the notebook, rerun, and see the effect on the output.

* Active rotation (https://dx.doi.org/10.1103/PhysRevLett.112.075701)
* **Suggest additional examples**

## Guides

A how-to guide notebook demonstrates a specific HOOMD feature with as succinct a script as possible along with explanatory markdown cells. There should be many short how-to guides organized  into subsections on similar topics. How-to guides should show the creation of the initial gsd file where relevant. Where not relevant, they may use an initial gsd file checked into the notebook repo (or re-use an initial gsd file created by another notebook). Output (plots and/or trajectories) must be examined so that the user may change parameters in the notebook and re-run to see the effect.

* Tabulated pair potential
* **What HOOMD features would you like to see guides for?**

## External tools

Notebooks in the external tools section demonstrate how to use HOOMD in conjunction tools such as (but not limited to) signac, mbuild, and freud.

* **What tools would you like to use HOOMD with?**

**Comment by vyasr** [comment]
Just FYI, I do plan to review this as soon as I have a bit more time.

**Comment by k-l-wang** [comment]
One of my biggest struggles with the HOOMD tutorials was that I had a hard time understanding how all the components of the tutorial fit together. This may be a matter of personal preference, but I like to understand how each of the topics relate to each other and the overall simulation before diving into the specifics of each feature. For the **Basic Tutorials**, I would suggest the following changes:
- Begin the tutorial with a brief overview of HOOMD and a simple simulation script. Use the simulation script to introduce concepts covered by the tutorial. Overviews before other topics would be helpful as well (ie, introduce hoomd.lattice and snapshots together or introduce integrators and the some of the avilable options before diving into a specific example). 
- Include links within the tutorial to guide users, links back to the index and/or topic page, and some sort of number/indexing to the notebooks names would make them easier to navigate. For example, a MD tutorial could suggest that you view a HPMC tutorial next or learn how to write output from the simulations. Numbers/indexing would make it easier to navigate the notebook files from a folder (The notebook to notebook links only work on nbviewer for me)

For **Guides**, I would have been interested to see one that sets pair potentials from a file using hoomd.md.pair.table. 

Would it be possible to have a set of how-to guides dedicated to showing the creation of initial GSD files for very general cases? Or maybe that would be something better suited for a HOOMD and signac demonstration.

**Comment by klywang** [comment]
I would be interested in a guide on how to use `hoomd.analyze.callback` to change simulation parameters based on some condition (ie, start to write a GSD file after x timesteps). 

Also, I'm not sure if this would be a bit redundant since there is already a guide on how to store particle shape information with `gsd`, but I think a guide on methods to dump particle data like particle potential energy or force could be helpful too. 

Would the tutorials I just suggested apply to others as well?
