### ISSUE TITLE
AttributeError: module 'hoomd' has no attribute 'device'

### ISSUE THREAD

**Issue by namus** [glotzerlab/hoomd-examples#36]
I have installed hoomd using conda as follows:
conda install -c conda-forge fresnel freud  gsd hoomd jupyterlab matplotlib

However, while trying to access the device in the notebooks (cpu = hoomd.device.CPU()), I get the following error:
AttributeError: module 'hoomd' has no attribute 'device'

hoomd.__version__
'2.9.6'

How do I resolve this issue? Thanks.

**Comment by cbkerr** [comment]
Install the beta version using the following command:

conda install -c conda-forge/label/hoomd_dev -c conda-forge hoomd

**Comment by namus** [comment]
> Install the beta version using the following command: conda install -c conda-forge/label/hoomd_dev -c conda-forge hoomd

Thanks! CPU version works now, but how do I install the GPU enabled beta version? I am getting the following error:
RuntimeError: This build of HOOMD does not include GPU support.

**Comment by namus** [comment]
conda install -c conda-forge/label/hoomd_dev -c conda-forge hoomd=*=*gpu*

... does not work, since it downgrades to conda-forge::hoomd-2.9.6-gpu_py38h3e5ef92_1

**Comment by joaander** [comment]
@namus As far as I know, `conda` should autodetect if you have a CUDA GPU and choose the GPU enabled package. Make sure you have upgraded to a recent version of conda.

@bdice Any thoughts on how to bypass the autodetect and force installation of the gpu dev package?

**Comment by bdice** [comment]
@namus Try this, perhaps it will work?

```bash
conda install -c conda-forge/label/hoomd_dev -c conda-forge hoomd=3.0.0dev7=gpu_py38*
```

**Comment by namus** [comment]
@bdice Yes, it worked. Thanks!
