### ISSUE TITLE
Choosing MD - Integrators

### ISSUE THREAD

**Issue by Tobias-Dwyer** [glotzerlab/hoomd-examples#48]
## Tutorial description
A tutorial showing the behavior of systems under different integrators.

## Section
We want each integrator showcasing each system at a high and low density and plot various physical quantities of each system. 

## Author
Tobias Dwyer
Josh Anderson

**Comment by joaander** [comment]
@Tobias-Dwyer Does this topic really warrant a full tutorial? What concepts would it teach?

I think it might be better to better explain how the different integration methods work in the API documentation for those methods.

**Comment by Tobias-Dwyer** [comment]
I think it would be worth teaching how to use each integrator for different applications and show that thermodynamic properties across integrators. Like how do you compute an equation of state and which method is better under which scenarios? I opened this PR when we were discussing how to demonstrate this in detail how to use each integrator. If we are just wanting to give users simple tips we could probs just put it in the documentation though, I agree.
