### ISSUE TITLE
Hard Spheres with hoomd v.3.0 API

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-examples#5]
## Example description
A simple simulation of hard spheres with trajectory dumping.

## Section
HPMC

## Tasks
- [x] Initialize system
- [x] run system
- [x] dump output

**Comment by yuanzhou0827** [comment]
@b-butler Hi Brandon, just want to make sure. The task here is to create a new .ipynb file that giving tutorial on how to dump trajectory for hard spheres simulation?

**Comment by b-butler** [comment]
@yuanzhou0827 I the task would be to create a .ipynb file that shows a hard sphere simulatin using the new API.

**Comment by joaander** [comment]
The new introduction to HOOMD tutorial demonstrates HPMC simulations.
