### ISSUE TITLE
Generate a Random Configuration

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-examples#6]
## Example description
Show how using freud to generate a random arrangement of particles with volume exclusion and creating a gsd file from the configuration.

## Section
Initialization

**Comment by bdice** [comment]
freud won't know anything about volume exclusion unless a user enforces that in their Python script.

That said, there is a function for generating a system with points randomly placed (uniformly) in an arbitrary box in `freud.data.make_random_system`:
https://freud.readthedocs.io/en/stable/modules/data.html#freud.data.make_random_system

**Comment by b-butler** [comment]
@bdice it doesn’t, but freud’s neighbor querying would allow to pick a random position and find out if it overlaps efficiently. Numpy or something else can generate the points.

**Comment by joaander** [comment]
For context: I am removing `deprecated.init.create_random` in v3.0 for two reasons. 1) HOOMD is a simulation engine, not an initialization engine. 2) It is inherently inflexible and really does not serve the needs of the user base well.

I intend to replace it with an example that users can copy and past and modify to meet their needs. Freud's neighbor list will be needed for efficient neighbor queries.

**Comment by syjlee** [comment]
Yein and I made a pull request about this issue.

**Comment by joaander** [comment]
The new v3 tutorials demonstrate initializing at low density and then running a short simulation to randomize. Do we still have a need to demonstrate a dart shooting particle placement method?

**Comment by syjlee** [comment]
@joaander I cannot think of specific use cases that need to generate initial random positions without running.
